### ISSUE TITLE
werkzeug error, which version should I pick for werkzeug?

### ISSUE THREAD

**Issue by cesarvspr** [b-ertel/Local-Binary-Pattern#1]
Error when starting application.

```bash
user@me:~/Documents/Local-Binary-Pattern$ python3 main.py 
Traceback (most recent call last):
  File "/home/user/Documents/Local-Binary-Pattern/main.py", line 1, in <module>
    import dash
  File "/home/user/.local/lib/python3.9/site-packages/dash/__init__.py", line 5, in <module>
    from .dash import Dash, no_update  # noqa: F401,E402
  File "/home/user/.local/lib/python3.9/site-packages/dash/dash.py", line 18, in <module>
    from werkzeug.debug.tbtools import get_current_traceback
ImportError: cannot import name 'get_current_traceback' from 'werkzeug.debug.tbtools' (/home/user/.local/lib/python3.9/site-packages/werkzeug/debug/tbtools.py)
```

**Comment by cesarvspr** [comment]
**SOLVED:**
Uninstall the wrong version with:
```bash
pip uninstall werkzeug
```

Install the right one with:
```bash
pip install -v https://github.com/pallets/werkzeug/archive/refs/tags/2.0.1.tar.gz
```
